@endpoint=http://localhost:8080

@admin= Bearer 

### 管理员登录
POST {{endpoint}}/api/sys/oauth/login

{
   "account": "admin",
   "password": "admin"
}


### 查询组织
GET {{endpoint}}/api/sys/org
Authorization: {{admin}}


## 查询组织
GET {{endpoint}}/api/sys/org
?search=客服
Authorization: {{admin}}
