@endpoint=http://localhost:8082

@admin= Bearer 

# ### 管理员登录
# POST {{endpoint}}/api/sys/oauth/login

# {
#    "account": "admin",
#    "password": "admin"
# }

### 查询组织树
GET {{endpoint}}/api/adm/org/tree?appid=1
Authorization: {{admin}} 


### 查询组织
GET {{endpoint}}/api/sys/org
Authorization: {{admin}}


## 查询组织
GET {{endpoint}}/api/sys/org
?search=客服
Authorization: {{admin}}
